#!/bin/bash

set -e
cd `dirname $0`
cd ..

mode=$1
version=$2
site=${mode}.rabbitmq.com
site_dir=srv/${site}

if [ $mode = www ] ; then
    community_plugins_dir=home/rabbitmq/extras/community-plugins/
    releases_dir=home/rabbitmq/extras/releases/

    xsltproc --novalid site/feed-atom.xsl site/news.xml > site/news.atom

    mkdir -p ${community_plugins_dir}
    ./code/find-community-plugins ${community_plugins_dir} site
elif [ $mode = previous ] ; then
    releases_dir=home/rabbitmq/extras/releases/
else
    releases_dir=home/rabbitmq/extras/nightlies/
fi

old_dir=`mktemp -d`
build_dir=`mktemp -d`

rm -rf $site_dir/site-src $site_dir/code ${build_dir}

mkdir -p $site_dir $site_dir/feeds
cp -r code $site_dir
cp -r site $site_dir/site-src

# TODO that "current" link is not created for nightlies
if [ $mode = www ] ; then
    if [ -d ${releases_dir}/rabbitmq-server/current/ ]; then
        cp -r ${releases_dir}/rabbitmq-server/current/man $site_dir/site-src/man
    fi
elif [ $mode = previous ] ; then
    version_pattern=${version/_/\.}
    version_pattern=${version_pattern%_*}
    version_pattern=${version_pattern//./\\.}\\.[0-9]
    youngest_match=$(find ${releases_dir}/rabbitmq-server -maxdepth 1 -type d -name "$version_pattern" | sort -V | tail -n 1)
    if [ x$youngest_match = x ] ; then
        echo "*** Note manpages not found. Please copy manually if necessary. ***"
    else
        cp -r $youngest_match/man $site_dir/site-src/man
    fi
fi

./code/compile $site_dir/site-src ${build_dir} $mode $version

csplit -s -f part ${build_dir}/templates/index.html /header-footer-horizon/
mv part00 ${build_dir}/templates/index-header.html
tail -n +2 part01 > ${build_dir}/templates/index-footer.html
rm ${build_dir}/templates/index.html part*

cp conf/robots.txt-${mode} ${build_dir}/robots.txt

if [ -d ${site_dir}/site/${version} ] ; then
    mv ${site_dir}/site/${version} ${old_dir}
fi

if [ ${mode} = previous ] ; then
    mkdir -p ${site_dir}/site
    mv ${build_dir} ${site_dir}/site/${version}
else
    mv ${build_dir} ${site_dir}/site
fi

rm -rf ${old_dir}
